In [ ]:
{"data":
 [{"shapeType":"rect","points":[{"x":225.83762886597935,"y":240.65721649484533},{"x":403.67268041237105,"y":240.65721649484533},{"x":403.67268041237105,"y":637.8865979381443},{"x":225.83762886597935,"y":637.8865979381443}],"info":[{"val":[{"realLabelValue":"人"}],"type":"tag"}]},
  {"shapeType":"rect","points":[{"x":310.88917525773195,"y":199.09793814432993},{"x":498.38917525773195,"y":199.09793814432993},{"x":498.38917525773195,"y":332.4742268041237},{"x":310.88917525773195,"y":332.4742268041237}],"info":[{"val":[{"realLabelValue":"十字花科"}],"type":"tag"}]}],
 "type":"PHOTO","info":[]}

In [ ]:
{"data":
 [{"shapeType":"rect","points":[{"x":225.83,"y":240.63},{"x":403.67,"y":240.65},{"x":403.65,"y":637.43},{"x":225.85,"y":637.43}],"info":[{"val":[{"realLabelValue":"动物"}],"type":"tags"}]}],
 "type":"PHOTO","info":[]}

In [ ]:

 [{"shapeType":"rect","points":[{"x":225.83,"y":240.63},{"x":403.67,"y":240.65},{"x":403.65,"y":637.43},{"x":225.85,"y":637.43}],"info":[{"val":[{"realLabelValue":"动物"}],"type":"tags"}]}],

In [5]:
import json
import pandas as pd
import numpy as np
import os


def func(s):
    try:
        return json.loads(s).get('data')
    except Exception as e:
        return []

os.chdir(r'F:\360MoveData\Users\Administrator\Desktop')
df = pd.read_excel('data.xlsx')
df['标注结果'] = df['标注结果'].apply(func)
df = df.explode('标注结果')
df.reset_index(drop=True, inplace=True)


def formatrow(row, s_column, r_columns):
    s = row[s_column]
    if isinstance(s, dict):
        return [s.get(r_column) for r_column in r_columns]


lables = ['shapeType', 'points', 'info']
df[lables] = df.apply(formatrow,
                      axis=1,
                      result_type="expand",
                      args=('标注结果', lables))
# df = df.explode('info')
# df['info'] = df['info'].apply(lambda s: s.get('val')
#                               if isinstance(s, dict) else None)
# df = df.explode('info')
# df['realLabelValue'] = df['info'].apply(lambda s: s.get('realLabelValue')
#                                         if isinstance(s, dict) else None)
# df.drop(columns=['标注结果', 'info'], inplace=True)
df

   序号 标注人员                                               标注结果
0   1   王二  {'shapeType': 'rect', 'points': [{'x': 225.837...
1   1   王二  {'shapeType': 'rect', 'points': [{'x': 310.889...
2   2   张三                                                NaN
3   3   李四  {'shapeType': 'rect', 'points': [{'x': 225.83,...

In [6]:
import json
import pandas as pd
import numpy as np
import os


os.chdir(r'F:\360MoveData\Users\Administrator\Desktop')
df = pd.read_excel("data.xlsx")

result = []
colum_dest = None
for i, row in df.iterrows():
    colums = row.index.values
    d = {}
    for colum in colums:
        try:
            json_o = json.loads(row[colum])
            d[colum] = json_o['data']
            colum_dest = colum
        except:
            d[colum] = row[colum]
    result.append(d)
df = pd.DataFrame(result)

df = df.explode(colum_dest)
df.reset_index(drop=True, inplace=True)


def formatrow(row, s_column, r_columns):
    s = row[s_column]
    if isinstance(s, dict):
        return [s.get(r_column) for r_column in r_columns]


lables = ['shapeType', 'points', 'info']
df[lables] = df.apply(formatrow,
                      axis=1,
                      result_type="expand",
                      args=(colum_dest, lables))
df = df.explode('info')
df['info'] = df['info'].apply(lambda s: s.get('val')
                              if isinstance(s, dict) else None)
df = df.explode('info')
df['realLabelValue'] = df['info'].apply(lambda s: s.get('realLabelValue')
                                        if isinstance(s, dict) else None)
df.drop(columns=[colum_dest, 'info'], inplace=True)
df

,序号,标注人员,shapeType,points,realLabelValue
0,1,王二,rect,"[{'x': 225.83762886597935, 'y': 240.6572164948...",人
1,1,王二,rect,"[{'x': 310.88917525773195, 'y': 199.0979381443...",十字花科
2,2,张三,None,None,None
3,3,李四,rect,"[{'x': 225.83, 'y': 240.63}, {'x': 403.67, 'y'...",动物